### ISSUE TITLE
Write (or find) a driver that converts received signal into cmd_vel

### ISSUE THREAD

**Issue by azan-m** [SEG4910-Capstone/ros-workspace#21] opened 2024-04-04 06:50 UTC
Xavier is going to be receiving this information through the GPIO pins using the i2c protocol. Danny will take care of the wireless transmission and receving, it will be upto us to parse the byte information that he's sends us through the GPIO pins. An Xbox controller will be used for transmission.

**Comment by MohanadAhmed123** [comment] 2024-04-09 23:17
Closing this issue as a duplicate of #22

**Closed by MohanadAhmed123** 2024-04-09 23:17 UTC
